version: "3.7"

services:

    flask:
        build: ./appdata
        container_name: flask_mailer
        restart: always
        env_file:
            - .env
        environment: 
            APP_NAME: hakromailing
            IDP_URI: ${IDP_URI}
            CLIENT_ID: ${CLIENT_ID}
            CLIENT_SECRET: ${CLIENT_SECRET}
            REDIRECT_URI: ${REDIRECT_URI}
            
        ports: 
            - "8085:8085"